# Generated by Django 5.0 on 2023-12-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
